// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lkwusyijeeizchlmapbu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxrd3VzeWlqZWVpemNobG1hcGJ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyMDI0NzAsImV4cCI6MjA3Mzc3ODQ3MH0.n6gXnxiMF2ssq4Hz8j7pJ37LXhsBJk7zitzepNvDQnA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});